/**
 * ProductRepositoryImpl Unit Tests
 * 
 * Tests for the ProductRepository implementation focusing on:
 * - Insert method functionality
 * - Row-to-entity mapping correctness
 * - JSONB parsing for images
 * - Numeric to number conversion for price
 * - Timestamp to Date conversion
 * 
 * **Validates: Requirements 1.6, 8.4**
 */

import { describe, it, expect, beforeEach, vi } from 'vitest';
import { ProductRepositoryImpl } from './product.repository.impl';
import { ProductEntity, ProductStatus } from '../entities/product.entity';

// Mock Supabase client
const createMockSupabaseClient = () => {
    const mockSelect = vi.fn().mockReturnThis();
    const mockSingle = vi.fn();
    const mockInsert = vi.fn().mockReturnThis();
    const mockFrom = vi.fn().mockReturnThis();

    return {
        from: mockFrom,
        mockSelect,
        mockSingle,
        mockInsert,
        // Helper to set up mock responses
        __setInsertResponse: (data: any, error: any = null) => {
            mockInsert.mockReturnValue({
                select: () => ({
                    single: () => Promise.resolve({ data, error })
                })
            });
        }
    };
};

describe('ProductRepositoryImpl', () => {
    describe('insert', () => {
        it('should insert a product and return mapped entity', async () => {
            // Arrange
            const mockClient = createMockSupabaseClient() as any;
            const repository = new ProductRepositoryImpl(mockClient);

            const productToInsert: ProductEntity = {
                id: '', // Will be generated by DB
                name: 'Test Product',
                description: 'Test Description',
                price: 99.99,
                category: 'Electronics',
                status: 'active' as ProductStatus,
                images: [
                    {
                        id: 'img-1',
                        url: 'https://example.com/image1.jpg',
                        filename: 'image1.jpg',
                        order: 0
                    }
                ],
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null
            };

            // Mock database response (snake_case with proper types)
            const mockDbRow = {
                id: '123e4567-e89b-12d3-a456-426614174000',
                name: 'Test Product',
                description: 'Test Description',
                price: '99.99', // Numeric comes as string from DB
                category: 'Electronics',
                status: 'active',
                images: JSON.stringify([
                    {
                        id: 'img-1',
                        url: 'https://example.com/image1.jpg',
                        filename: 'image1.jpg',
                        order: 0
                    }
                ]),
                created_at: '2024-01-15T10:30:00.000Z',
                updated_at: '2024-01-15T10:30:00.000Z',
                deleted_at: null
            };

            mockClient.__setInsertResponse(mockDbRow);

            // Act
            const result = await repository.insert(productToInsert);

            // Assert
            expect(result).toBeDefined();
            expect(result.id).toBe('123e4567-e89b-12d3-a456-426614174000');
            expect(result.name).toBe('Test Product');
            expect(result.description).toBe('Test Description');
            expect(result.price).toBe(99.99); // Should be number, not string
            expect(typeof result.price).toBe('number');
            expect(result.category).toBe('Electronics');
            expect(result.status).toBe('active');
            expect(result.images).toHaveLength(1);
            expect(result.images[0].id).toBe('img-1');
            expect(result.createdAt).toBeInstanceOf(Date);
            expect(result.updatedAt).toBeInstanceOf(Date);
            expect(result.deletedAt).toBeNull();
        });

        it('should handle JSONB images as already-parsed object', async () => {
            // Arrange
            const mockClient = createMockSupabaseClient() as any;
            const repository = new ProductRepositoryImpl(mockClient);

            const productToInsert: ProductEntity = {
                id: '',
                name: 'Test Product',
                description: null,
                price: 49.99,
                category: 'Books',
                status: 'active' as ProductStatus,
                images: [],
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null
            };

            // Mock database response with images as already-parsed object
            const mockDbRow = {
                id: '123e4567-e89b-12d3-a456-426614174001',
                name: 'Test Product',
                description: null,
                price: 49.99, // Numeric as number
                category: 'Books',
                status: 'active',
                images: [
                    {
                        id: 'img-2',
                        url: 'https://example.com/image2.jpg',
                        filename: 'image2.jpg',
                        order: 0
                    }
                ], // Already parsed
                created_at: '2024-01-15T10:30:00.000Z',
                updated_at: '2024-01-15T10:30:00.000Z',
                deleted_at: null
            };

            mockClient.__setInsertResponse(mockDbRow);

            // Act
            const result = await repository.insert(productToInsert);

            // Assert
            expect(result.images).toHaveLength(1);
            expect(result.images[0].id).toBe('img-2');
        });

        it('should handle empty images array', async () => {
            // Arrange
            const mockClient = createMockSupabaseClient() as any;
            const repository = new ProductRepositoryImpl(mockClient);

            const productToInsert: ProductEntity = {
                id: '',
                name: 'Test Product',
                description: null,
                price: 29.99,
                category: 'Accessories',
                status: 'active' as ProductStatus,
                images: [],
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null
            };

            const mockDbRow = {
                id: '123e4567-e89b-12d3-a456-426614174002',
                name: 'Test Product',
                description: null,
                price: '29.99',
                category: 'Accessories',
                status: 'active',
                images: '[]', // Empty JSONB array
                created_at: '2024-01-15T10:30:00.000Z',
                updated_at: '2024-01-15T10:30:00.000Z',
                deleted_at: null
            };

            mockClient.__setInsertResponse(mockDbRow);

            // Act
            const result = await repository.insert(productToInsert);

            // Assert
            expect(result.images).toEqual([]);
            expect(Array.isArray(result.images)).toBe(true);
        });

        it('should throw error on unique constraint violation', async () => {
            // Arrange
            const mockClient = createMockSupabaseClient() as any;
            const repository = new ProductRepositoryImpl(mockClient);

            const productToInsert: ProductEntity = {
                id: '',
                name: 'Duplicate Product',
                description: null,
                price: 99.99,
                category: 'Electronics',
                status: 'active' as ProductStatus,
                images: [],
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null
            };

            // Mock unique constraint violation error
            const mockError = {
                code: '23505',
                message: 'duplicate key value violates unique constraint'
            };

            mockClient.__setInsertResponse(null, mockError);

            // Act & Assert
            await expect(repository.insert(productToInsert)).rejects.toThrow(
                "A product with name 'Duplicate Product' already exists in category 'Electronics'."
            );
        });

        it('should parse numeric price from string correctly', async () => {
            // Arrange
            const mockClient = createMockSupabaseClient() as any;
            const repository = new ProductRepositoryImpl(mockClient);

            const productToInsert: ProductEntity = {
                id: '',
                name: 'Price Test Product',
                description: null,
                price: 123.45,
                category: 'Test',
                status: 'active' as ProductStatus,
                images: [],
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null
            };

            const mockDbRow = {
                id: '123e4567-e89b-12d3-a456-426614174003',
                name: 'Price Test Product',
                description: null,
                price: '123.45', // String representation of numeric
                category: 'Test',
                status: 'active',
                images: '[]',
                created_at: '2024-01-15T10:30:00.000Z',
                updated_at: '2024-01-15T10:30:00.000Z',
                deleted_at: null
            };

            mockClient.__setInsertResponse(mockDbRow);

            // Act
            const result = await repository.insert(productToInsert);

            // Assert
            expect(result.price).toBe(123.45);
            expect(typeof result.price).toBe('number');
        });

        it('should parse timestamps to Date objects correctly', async () => {
            // Arrange
            const mockClient = createMockSupabaseClient() as any;
            const repository = new ProductRepositoryImpl(mockClient);

            const productToInsert: ProductEntity = {
                id: '',
                name: 'Timestamp Test Product',
                description: null,
                price: 50.00,
                category: 'Test',
                status: 'active' as ProductStatus,
                images: [],
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null
            };

            const mockDbRow = {
                id: '123e4567-e89b-12d3-a456-426614174004',
                name: 'Timestamp Test Product',
                description: null,
                price: '50.00',
                category: 'Test',
                status: 'active',
                images: '[]',
                created_at: '2024-01-15T10:30:00.000Z',
                updated_at: '2024-01-15T11:45:00.000Z',
                deleted_at: null
            };

            mockClient.__setInsertResponse(mockDbRow);

            // Act
            const result = await repository.insert(productToInsert);

            // Assert
            expect(result.createdAt).toBeInstanceOf(Date);
            expect(result.updatedAt).toBeInstanceOf(Date);
            expect(result.createdAt.toISOString()).toBe('2024-01-15T10:30:00.000Z');
            expect(result.updatedAt.toISOString()).toBe('2024-01-15T11:45:00.000Z');
            expect(result.deletedAt).toBeNull();
        });
    });
});
